
package com.johnkuper.epam.client;

import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JPAWebServiceImpl", targetNamespace = "http://jpa.johnkuper/jpawebservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JPAWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.johnkuper.epam.client.CarWeb>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCarByName", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarByName")
    @ResponseWrapper(localName = "findCarByNameResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarByNameResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarByNameRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarByNameResponse")
    public List<CarWeb> findCarByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.SayHiResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/sayHiRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
