
package com.johnkuper.epam.client;

import java.math.BigDecimal;
import java.util.List;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "JPAWebServiceImpl", targetNamespace = "http://jpa.johnkuper/jpawebservice")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface JPAWebServiceImpl {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "sayHi", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.SayHi")
    @ResponseWrapper(localName = "sayHiResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.SayHiResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/sayHiRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/sayHiResponse")
    public String sayHi(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.util.List<com.johnkuper.epam.client.CarWeb>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCarByName", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarByName")
    @ResponseWrapper(localName = "findCarByNameResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarByNameResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarByNameRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarByNameResponse")
    public List<CarWeb> findCarByName(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCar", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateCar")
    @ResponseWrapper(localName = "createCarResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateCarResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createCarRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createCarResponse")
    public String createCar(
        @WebParam(name = "arg0", targetNamespace = "")
        CarWeb arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createCustomer", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateCustomer")
    @ResponseWrapper(localName = "createCustomerResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateCustomerResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createCustomerRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createCustomerResponse")
    public String createCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        CustomerWeb arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.johnkuper.epam.client.CustomerWeb
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCustomer", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCustomer")
    @ResponseWrapper(localName = "findCustomerResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCustomerResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCustomerRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCustomerResponse")
    public CustomerWeb findCustomer(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.johnkuper.epam.client.MerchantWeb
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findMerchant", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindMerchant")
    @ResponseWrapper(localName = "findMerchantResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindMerchantResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findMerchantRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findMerchantResponse")
    public MerchantWeb findMerchant(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "createMerchant", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateMerchant")
    @ResponseWrapper(localName = "createMerchantResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.CreateMerchantResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createMerchantRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/createMerchantResponse")
    public String createMerchant(
        @WebParam(name = "arg0", targetNamespace = "")
        MerchantWeb arg0);

    /**
     * 
     * @param arg3
     * @param arg2
     * @param arg1
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "buyCar", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.BuyCar")
    @ResponseWrapper(localName = "buyCarResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.BuyCarResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/buyCarRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/buyCarResponse")
    public String buyCar(
        @WebParam(name = "arg0", targetNamespace = "")
        CarWeb arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        CustomerWeb arg1,
        @WebParam(name = "arg2", targetNamespace = "")
        MerchantWeb arg2,
        @WebParam(name = "arg3", targetNamespace = "")
        BigDecimal arg3);

    /**
     * 
     * @param arg1
     * @param arg0
     * @return
     *     returns java.util.List<com.johnkuper.epam.client.CarWeb>
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "findCarsByMotorPower", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarsByMotorPower")
    @ResponseWrapper(localName = "findCarsByMotorPowerResponse", targetNamespace = "http://jpa.johnkuper/jpawebservice", className = "com.johnkuper.epam.client.FindCarsByMotorPowerResponse")
    @Action(input = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarsByMotorPowerRequest", output = "http://jpa.johnkuper/jpawebservice/JPAWebServiceImpl/findCarsByMotorPowerResponse")
    public List<CarWeb> findCarsByMotorPower(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        int arg1);

}
